### PR TITLE
Color preview in editor

### PR DESCRIPTION
**Pull request by jfgartol**

### CODE REVIEW

**Comment by bentorkington** [comment]
oh yes! I wanted to do this, tried and got lost. This looks great, thanks for doing it!

edit: looks like you disabled the tests though. Perhaps commit without commenting out test/index.ts?

**Comment by kennebel** [comment]
Great, I'll finish up the unit testing changes, and get these integrated as well. Thank you.

**Comment by jfgartol** [comment]
> oh yes! I wanted to do this, tried and got lost. This looks great, thanks for doing it!
> 
> edit: looks like you disabled the tests though. Perhaps commit without commenting out test/index.ts?

Hello, thanks for the comment, I get an error in this file that I don't know how to solve, the error is this:
src/test/index.ts:13:29 - error TS2307: Cannot find module 'vscode/lib/testrunner' or its corresponding type declarations.

**Comment by kennebel** [comment]
The test framework has changed since the last release of this project, so I have to convert. Someone was kind enough to give me some steps to take, I just need to find a few minutes to execute their suggestion.

**Comment by kennebel** [comment]
Going on a trip, and will get this PR merged when I return.

**Pull request merged**
